VendendoPecas/Models/ErrorViewModel.cs
namespace VendendoPecas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

VendendoPecas/Models/VendasModel.cs
using System.ComponentModel.DataAnnotations;

namespace VendendoPecas.Models
{
    public class VendasModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o nome do Comprador!")]
        public string Comprador { get; set; }

        [Required(ErrorMessage = "Digite o nome do Vendedor!")]
        public string Vendedor { get; set; }

        [Required(ErrorMessage = "Digite o nome da Peça Vendida!")]
        public string PecaVendida { get; set; }

        public DateTime DataVenda { get; set; }
    }
}

VendendoPecas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using VendendoPecas.Models;

namespace VendendoPecas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

VendendoPecas/Controllers/VendaController.cs
using ClosedXML.Excel;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using VendendoPecas.Data;
using VendendoPecas.Models;

namespace VendendoPecas.Controllers
{
    public class VendaController : Controller
    {
        readonly private ApplicationDbContext _db;

        public VendaController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public IActionResult Index()
        {
            IEnumerable<VendasModel> vendas = _db.Vendas;
            return View(vendas);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            VendasModel vendas = _db.Vendas.FirstOrDefault(x => x.Id == id);

            if (vendas == null)
            {
                return NotFound();
            }

            return View(vendas);
        }

        [HttpGet]
        public IActionResult Excluir(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }

            VendasModel vendas = _db.Vendas.FirstOrDefault(x => x.Id == id);

            if (vendas == null)
            {
                return NotFound();
            }

            return View(vendas);
        }

        [HttpGet]
        public IActionResult Exportar()
        {
            var dados = GetDados();

            using (XLWorkbook workbook = new XLWorkbook())
            {
                workbook.AddWorksheet(dados, "Dados Vendas");

                using (MemoryStream ms = new MemoryStream())
                {
                    workbook.SaveAs(ms);

                    return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spredsheetml.sheet", "Vendas.xls");
                }
            }
        }

        private DataTable GetDados()
        {
            DataTable dt = new DataTable();

            dt.TableName = "Dados Vendas";

            dt.Columns.Add("Comprador", typeof(string));
            dt.Columns.Add("Vendedor", typeof(string));
            dt.Columns.Add("Peça Vendida", typeof(string));
            dt.Columns.Add("Data Atualização", typeof(DateTime));

            var dados = _db.Vendas.ToList();

            if (dados.Count > 0)
            {
                dados.ForEach(venda =>
                {
                    dt.Rows.Add(venda.Comprador, venda.Vendedor, venda.PecaVendida, venda.DataVenda);
                });
            }

            return dt;
        }

        [HttpPost]
        public IActionResult Cadastrar(VendasModel vendas)
        {
            if (ModelState.IsValid)
            {
                vendas.DataVenda = DateTime.Now;

                _db.Vendas.Add(vendas);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Cadastro realizado com sucesso!";

                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost]
        public IActionResult Editar(VendasModel venda)
        {
            if (ModelState.IsValid)
            {
                var vendaDB = _db.Vendas.Find(venda.Id);

                vendaDB.Comprador = venda.Comprador;
                vendaDB.Vendedor = venda.Vendedor;
                vendaDB.PecaVendida = venda.PecaVendida;

                _db.Vendas.Update(vendaDB);
                _db.SaveChanges();

                TempData["MensagemSucesso"] = "Edição realizado com sucesso!";

                return RedirectToAction("Index");
            }

            TempData["MensagemErro"] = "Algum erro ocorreu ao realizar a edição!";

            return View(venda);
        }

        [HttpPost]
        public IActionResult Excluir(VendasModel venda)
        {
            if (venda == null)
            {
                return NotFound();
            }

            _db.Vendas.Remove(venda);
            _db.SaveChanges();

            TempData["MensagemSucesso"] = "Exclusão realizada com sucesso!";

            return RedirectToAction("Index");
        }
    }
}

VendendoPecas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Início";
}

<div class="text-center">
    <h1 class="display-4">Vendendo Peças Automotivas</h1>
    <p>Otimize suas vendas e mantenha um controle preciso de seu inventário exclusivamente <br />
       através do nosso portal dedicado aos vendedores de peças automotivas.</p>
    <div>
        <img src="img/pecas_automotivas.png"/></imgf>
    </div>
</div>

VendendoPecas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/Materia.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VendendoPecas.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.datatables.net/v/dt/dt-2.0.5/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-wrench mx-2"></i>Vendendo Peças Automotivas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house-fill mx-2"></i>Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Venda" asp-action="Index"><i class="bi bi-cart4 mx-2"></i>Vendas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class="container text-light">
            &copy; 2024 - Vendendo Peças Automotivas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-2.0.5/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VendendoPecas/Views/Venda/Cadastrar.cshtml
@model VendasModel
@{
    ViewData["title"] = "Cadastrar Venda";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de Vendas</h1>
    </div>

    <form method="post" asp-controller="Venda" asp-action="Cadastrar">
        <div class="mb-3">
            <label for="Comprador" class="form-label text-light">Comprador:</label>
            <input type="text" class="form-control text-light" asp-for="Comprador" id="Comprador" placeholder="Quem está comprando?" />
            <span class="text-danger" asp-validation-for="Comprador"></span>
        </div>

        <div class="mb-3">
            <label for="Vendedor" class="form-label text-light">Vendedor:</label>
            <input type="text" class="form-control text-light" asp-for="Vendedor" id="Vendedor" placeholder="Quem está vendendo?" />
            <span class="text-danger" asp-validation-for="Vendedor"></span>
        </div>

        <div class="mb-3">
            <label for="PecaVendida" class="form-label text-light">Nome da Peça:</label>
            <input type="text" class="form-control text-light" asp-for="PecaVendida" id="PecaVendida" placeholder="Qual peça está sendo vendida?" />
            <span class="text-danger" asp-validation-for="PecaVendida"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <a class="btn btn-primary w-50" asp-controller="Venda" asp-action="Index">Voltar</a>
            <button type="submit" class="btn btn-success w-50">Cadastrar</button>
        </div>
    </form>
</div>

VendendoPecas/Views/Venda/Editar.cshtml
@model VendasModel
@{
    ViewData["title"] = "Editar Venda";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de Venda</h1>
    </div>

    <form method="post" asp-controller="Venda" asp-action="Editar">
        <input type="hidden" asp-for="Id"/>

        <div class="mb-3">
            <label for="Comprador" class="form-label text-light">Comprador:</label>
            <input type="text" class="form-control text-light" asp-for="Comprador" id="Comprador" placeholder="Quem está comprando?" />
            <span class="text-danger" asp-validation-for="Comprador"></span>
        </div>

        <div class="mb-3">
            <label for="Vendedor" class="form-label text-light">Vendedor:</label>
            <input type="text" class="form-control text-light" asp-for="Vendedor" id="Vendedor" placeholder="Quem está vendendo?" />
            <span class="text-danger" asp-validation-for="Vendedor"></span>
        </div>

        <div class="mb-3">
            <label for="PecaVendida" class="form-label text-light">Nome da Peça:</label>
            <input type="text" class="form-control text-light" asp-for="PecaVendida" id="PecaVendida" placeholder="Qual peça está sendo vendida?" />
            <span class="text-danger" asp-validation-for="PecaVendida"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <a class="btn btn-primary w-50" asp-controller="Venda" asp-action="Index">Voltar</a>
            <button type="submit" class="btn btn-success w-50">Editar</button>
        </div>
    </form>
</div>

VendendoPecas/Views/Venda/Excluir.cshtml
@model VendasModel
@{
    ViewData["title"] = "Excluir Venda";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Exclusão de Venda</h1>
    </div>

    <form method="post" asp-controller="Venda" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />

        <h2 class="text-danger mb-4">Tem certeza que deseja excluir a venda?</h2>

        <div class="mb-3">
            <label for="Comprador" class="form-label text-light">Comprador:</label>
            <input type="text" class="form-control text-light" asp-for="Comprador" id="Comprador" placeholder="Quem está comprando?" disabled />
            <span class="text-danger" asp-validation-for="Comprador"></span>
        </div>

        <div class="mb-3">
            <label for="Vendedor" class="form-label text-light">Vendedor:</label>
            <input type="text" class="form-control text-light" asp-for="Vendedor" id="Vendedor" placeholder="Quem está vendendo?" disabled />
            <span class="text-danger" asp-validation-for="Vendedor"></span>
        </div>

        <div class="mb-3">
            <label for="PecaVendida" class="form-label text-light">Nome da Peça:</label>
            <input type="text" class="form-control text-light" asp-for="PecaVendida" id="PecaVendida" placeholder="Qual peça está sendo vendida?" disabled />
            <span class="text-danger" asp-validation-for="PecaVendida"></span>
        </div>

        <div class="d-flex gap-5 mt-5">
            <a class="btn btn-primary w-50" asp-controller="Venda" asp-action="Index">Voltar</a>
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
        </div>
    </form>
</div>

VendendoPecas/Views/Venda/Index.cshtml
@model IEnumerable<VendasModel>

@{
    ViewData["title"] = "Vendas";
}

<div class="container">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h1>Vendas</h1>
        <div>
            <a class="btn btn-success mx-2" asp-controller="Venda" asp-action="Exportar"><i class="bi bi-cloud-download mx-2"></i></i>Exportar</a>
            <a class="btn btn-success mx-2" asp-controller="Venda" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus mx-2"></i>Cadastrar nova venda</a>
        </div>
    </div>

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }

    <table class="table table-light table-hover mt-4" id="Vendas">
        <thead>
            <tr>
                <th scope="col">Comprador</th>
                <th scope="col">Vendedor</th>
                <th scope="col">Peça</th>
                <th scope="col">Data Venda</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                @foreach (var venda in Model)
                {
                    <tr>
                        <td scope="row">@venda.Comprador</td>
                        <td scope="row">@venda.Vendedor</td>
                        <td scope="row">@venda.PecaVendida</td>
                        <td scope="row">@venda.DataVenda</td>
                        <td>
                            <a asp-controller="Venda" asp-action="Editar" asp-route-id="@venda.Id" class="btn btn-warning mx-2"><i class="bi bi-pencil-square mx-2"></i>Editar</a>
                            <a asp-controller="Venda" asp-action="Excluir" asp-route-id="@venda.Id" class="btn btn-danger mx-2"><i class="bi bi-trash-fill mx-2"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
    </table>
</div>